#!/bin/bash
if [ $# -lt 4 ]; then
    echo "Usage: $0 <From> <To> [Cc] <Subject> <Text>"
    exit 1
fi
if [ $# -eq 4 ]; then
    echo "Text: $4" > mail.txt
    echo "From: $1" >> mail.txt
    echo "To: $2" >> mail.txt
    echo "Subject: $3" >> mail.txt
    echo This email is generated by my script. >> mail.txt
    echo Thanks and Regards >> mail.txt
    echo S4 CSE D >> mail.txt
    echo Amritapuri >> mail.txt
    exit 0
fi
if [ $# -eq 5 ]; then
    echo "Text: $5" > mail.txt
    echo "From: $1" >> mail.txt
    echo "To: $2" >> mail.txt
    echo "Cc: $3" >> mail.txt
    echo "Subject: $4" >> mail.txt
    echo $5 >> mail.txt
    echo Thanks and Regards >> mail.txt
    echo S4 CSE D >> mail.txt
    echo Amritapuri >> mail.txt
    exit 0
fi