CREATE TABLE DOCTOR
(
    DID INT PRIMARY KEY,
    DNAME VARCHAR(25),
    SPECIALIZATION VARCHAR(20) DEFAULT'GENERAL',
    AADHAR_NO VARCHAR(12),
    CONSULTATION_FEES NUMERIC(5,2),
    CITYVAR CHAR(20),
    UNIQUE(AADHAR_NO),
    CONSTRAINT C1 CHECK(CONSULTATION_FEES>50)
);
CREATE TABLE PATIENT 
(
    PID INT PRIMARY KEY,
    PNAME VARCHAR(25),
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(20)
);
CREATE TABLE TREATMENT 
(
    DID INT,
    PID INT,
    DIAGNOSIS VARCHAR(30)NOT NULL,
    TREAT_ID INT,
    TREAT_DATE DATE,
    FOREIGN KEY(DID) REFERENCESDOCTOR ON DELETE CASCADE,
    FOREIGN KEY(PID) REFERENCESPATIENT ON DELETE SET NULL
);
INSERT INTO DOCTOR 
    (DID, DNAME, AADHAR_NO, CONSULTATION_FEE, CITY) 
VALUES
    ( 1 , 'RAY', '123456789', 111, 'MUMBAI'),
    ( 2 , 'NELL','123456788', 251, 'DELHI'), 
    ( 3 , 'BELL', ‘123456787’,100,'BANGALORE'), 
    ( 4 , 'BILL', '7785425899', 320, 'HYDERABAD'), 
    ( 5 , 'RONNY', '5522631258', 410, 'AHMEDABAD'), 
    ( 6 , 'JIMMY', '7412583214', 203, 'PUNE'), 
    ( 7 , 'CARL', '2235216325', 520, 'PATNA');
ALTER TABLE DOCTOR
ADD SPECIAL NUMERIC(5,2)
UPDATE DOCTOR SET SPECIAL_FEE = 250;
ALTER TABLE DOCTOR
ADD CHECK(SPECIAL_FEE > CONSULTATION_FEE);
ALTER TABLE DOCTOR
DROP CONSTRAINT C1;
ALTER TABLE PATIENT
ADD AADHAR_NUMBER Numeric(12)UNIQUE;
ALTER TABLE PATIENT
ALTER COLUMN DATE_OF_BIRTH SET NOT NULL;
ALTER TABLE TREATMENT
ADD CONSTRAINT CON1 UNIQUE(TREAT_ID, TREAT_DATE);
INSERT INTO TREATMENT 
    (DID, PID, DIAGNOSIS, TREAT_ID, TREAT_DATE) 
VALUES
    ( 1 , 111 , 'Biopsy', 021 ,'2020-11-11'),
    ( 2 , 112 , 'Colonoscopy', 321 ,'2022-11-09'), 
    (1 , 113 , 'CT scan', 754 ,'2000-11-11'), 
    ( 4 , 114 , 'Electrocardiogram', 964 ,'1908-10-29'), 
    ( 5 , 115 , 'Electroencephalogram', 352 ,'2006-09-26'),
    ( 6 , 116 , 'Gastroscopy', 456 ,'2016-10-26'), 
    ( 7 , 117 , 'MRI scan', 126 ,'2007-06-20');
DELETE FROM DOCTOR 
WHERE DNAME = 'Ray';
SELECT DNAME 
FROM DOCTOR 
WHERE CONSULTATION_FEE % 2 = 0;
SELECT DNAME 
FROM DOCTOR 
WHERE DNAME LIKE'K%n';
SELECT PNAME 
FROM PATIENT 
WHERE PNAME LIKE'A__';
SELECT DNAME 
FROM DOCTOR 
WHERE PNAME LIKE'J%'OR PNAME LIKE'L%';
SELECT DNAME 
FROM DOCTOR 
WHERE SPECIALIZATION = 'E.N.T' AND CONSULTATION_FEE > 60;
SELECT DNAME 
FROM DOCTOR 
WHERE CONSULTATION_FEE BETWEEN 50 AND 100;
SELECT * 
FROM DOCTOR 
ORDER BY CITY DESC;
SELECT DISTINCT SPECIALIZATION 
FROM DOCTOR;
SELECT COUNT(DNAME) 
FROM DOCTOR;
SELECT COUNT(DNAME) 
FROM DOCTOR 
WHERE SPECIALIZATION = 'E.N.T';
SELECT COUNT(PID) 
FROM TREATMENT 
WHERE DID = 1;
SELECT DNAME 
FROM DOCTOR 
WHERE SPECIALIZATION IN('E.N.T','Cardiac','Paediatrics');
SELECT 
    AVG(CONSULTATION_FEE), 
    MAX(CONSULTATION_FEE), 
    MIN(CONSULTATION_FEE) 
FROM DOCTOR;
SELECT SUM(SPECIAL_FEE) 
FROM DOCTOR 
WHERE SPECIALIZATION = 'Paediatrics';
ALTER TABLE DOCTOR 
RENAME COLUMN DNAME TO DOCTOR_NAME;
SELECT *
FROM DOCTOR;
SELECT DID, DNAME, (CONSULTATION_FEE + SPECIAL_FEE) ASTOTAL_FEES 
FROM DOCTOR;
SELECT COUNT(DID) 
FROM DOCTOR 
WHERE AADHAR_NO IS NULL;
SELECT COUNT(DID) 
FROM DOCTOR 
WHERE AADHAR_NO IS NOT NULL;
SELECT DNAME 
FROM DOCTOR 
WHERE CONSULTATION_FEE > 100 AND SPECIALIZATION = 'Cardiac' OR CITY = 'Kollam';
SELECT * 
FROM DOCTOR 
ORDER BY 3;
SELECT CONCAT(DNAME,' is specialized in ',SPECIALIZATION) 
FROM DOCTOR;